// metric types: 'total_deeds' | 'total_tokens' | 'streak' | 'days_logged' | 'area_deeds' | 'all_areas'
export const BUILTIN_BADGES = [
  {
    id: 'first-step',
    name: 'First Step',
    icon: '🌱',
    desc: 'Log your very first deed',
    metric: 'total_deeds',
    threshold: 1,
  },
  {
    id: 'weekly-warrior',
    name: 'Weekly Warrior',
    icon: '🔥',
    desc: 'Maintain a 7-day streak',
    metric: 'streak',
    threshold: 7,
  },
  {
    id: 'fortnight',
    name: 'Fortnight',
    icon: '⚡',
    desc: 'Maintain a 14-day streak',
    metric: 'streak',
    threshold: 14,
  },
  {
    id: 'monthly-marvel',
    name: 'Monthly Marvel',
    icon: '🏆',
    desc: 'Maintain a 30-day streak',
    metric: 'streak',
    threshold: 30,
  },
  {
    id: 'centurion',
    name: 'Centurion',
    icon: '💯',
    desc: 'Log 100 total deeds',
    metric: 'total_deeds',
    threshold: 100,
  },
  {
    id: 'token-rich',
    name: 'Token Rich',
    icon: '💎',
    desc: 'Earn 500 total tokens',
    metric: 'total_tokens',
    threshold: 500,
  },
  {
    id: 'token-legend',
    name: 'Token Legend',
    icon: '👑',
    desc: 'Earn 1000 total tokens',
    metric: 'total_tokens',
    threshold: 1000,
  },
  {
    id: 'all-rounder',
    name: 'All-Rounder',
    icon: '❄️',
    desc: 'Log a deed in all 11 life areas',
    metric: 'all_areas',
    threshold: 1,
  },
  {
    id: 'social-star',
    name: 'Social Star',
    icon: '🌟',
    desc: 'Log 10 deeds in Social',
    metric: 'area_deeds',
    area: 'social',
    threshold: 10,
  },
  {
    id: 'fitness-fanatic',
    name: 'Fitness Fanatic',
    icon: '💪',
    desc: 'Log 20 deeds in Fitness',
    metric: 'area_deeds',
    area: 'fitness',
    threshold: 20,
  },
  {
    id: 'finance-wizard',
    name: 'Finance Wizard',
    icon: '💰',
    desc: 'Log 10 deeds in Finance',
    metric: 'area_deeds',
    area: 'finance',
    threshold: 10,
  },
  {
    id: 'goal-crusher',
    name: 'Goal Crusher',
    icon: '🎯',
    desc: 'Log 20 deeds in Goals',
    metric: 'area_deeds',
    area: 'goals',
    threshold: 20,
  },
];
