export const BUILTIN_QUOTES = [
  'Small actions, consistently taken, build extraordinary lives.',
  'Every deed you log is a promise kept to yourself.',
  'Progress isn\'t always loud — sometimes it\'s a quiet note in a journal.',
  'You don\'t have to do everything today. Just one thing.',
  'The snowflake grows one crystal at a time.',
  'Consistency is a quiet superpower.',
  'Done is better than perfect; logged is better than forgotten.',
  'The gap between who you are and who you want to be is filled with small acts.',
  'What you track, you tend to improve.',
  'A streak isn\'t just a number — it\'s evidence of who you\'re becoming.',
  'Good habits are worth celebrating, even when no one\'s watching.',
  'Growth isn\'t linear, but it is cumulative.',
  'Today\'s small win is tomorrow\'s foundation.',
  'Be patient with yourself — snowflakes don\'t form all at once.',
  'The best time to log a good deed is right after you do it.',
  'You are building something. Every entry matters.',
  'Kindness to yourself is as important as kindness to others.',
  'What would you tell your future self you did today?',
];
